// composer require laravel-fullcalendar
<php 
'providers' => [
	....
	....
	MaddHatter\LaravelFullcalendar\ServiceProvider::class,
],
 
'aliases' => [
	....
	....
	'Calendar' => MaddHatter\LaravelFullcalendar\Facades\Calendar::class,
]
